name: develop

on:
  push:
    branches:
      - 'develop'

jobs:
  build_dotnet:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet build

  test_dotnet:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test -p:CollectCoverage=true -p:CoverletOutPutFormat=opencover

  package_dotnet:
    runs-on: ubuntu-20.04
    needs: [build_dotnet, test_dotnet]
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      - run: docker image build -t ${DOCKER_REPO} .
      - run: docker image tag ${DOCKER_REPO} cvchavez2/tictactoe-dotnet
      - run: docker image push cvchavez2/tictactoe-dotnet
      - run: docker logout